on:
    push:
      branches: 
      - master
jobs:
    pruebasE2E:
        name: Desplegando el ambiente
        runs-on: ubuntu-latest
        steps:
        - name: Comprobacion del codigo
          uses: actions/checkout@v4

        - name: Instalando el entorno de NodeJS
          uses: actions/setup-node@v6.0.0
            
        - name: Instalando PNPM
          run: npm install -g pnpm

        - name: Instalando las dependencias con PNPM
          run: pnpm install --frozen-lockfile
          
        - name: Instalando Playwright
          run: pnpm exec playwright install --with-deps
          
        - name: Ejecutando los tests
          run: pnpm playwright test --project=chromium

        - name: Exportando los resultados
          uses: actions/upload-artifact@v4
          if: ${{ always() }} # Se ejecuta incluso si las pruebas fallan o son canceladas
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
